admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
file_explorer:
    path:      /{page}
    defaults:  { _controller: AppBundle:Default:index , page:1}
    requirements:
        page: '\d+'
